Print factored count over candidates count
FACT0RN/factoring pull request #21
Opened 2022-10-07 22:39 UTC by daedalus

2022-10-13 22:42 UTC, ReverseControl commented on python/FACTOR.py
> +                        print("Factored: %d of %d" % (self.Count, len(candidates))
Missing a parenthesis.

2022-10-13 22:44 UTC, ReverseControl requested changes
Looks good. Just fix the missing parenthesis of the print statement. You might also want to print that stat above the "Total lost time" line and not below.

2022-10-13 22:53 UTC, daedalus commented on python/FACTOR.py
> +                        print("Factored: %d of %d" % (self.Count, len(candidates))
Fixed

2022-10-13 22:54 UTC, daedalus commented
Plase take a look at the latest commit.

2022-10-19 00:10 UTC, ReverseControl commented on python/FACTOR.py
> +
You need to leave this here. This count should be initialized to zero every time we enter this function. If it is not globally defined line 620 will throw an error, and even if it is the printed value performed in line 620 will be wrong. So, initialize to zero here.

2022-10-30 18:00 UTC, ReverseControl commented on python/FACTOR.py
> +
@daedalus

2022-11-08 22:25 UTC, closed without merging